onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /core/clk
add wave -noupdate /core/reset
add wave -noupdate /core/flush
add wave -noupdate /core/instruction_to_decode
add wave -noupdate /core/PCnext_to_decode
add wave -noupdate /core/RegAdata_to_alu
add wave -noupdate /core/RegBdata_to_alu
add wave -noupdate /core/lower_half_instruction_to_alu
add wave -noupdate /core/WB_EN_TO_ALU
add wave -noupdate /core/MEM_R_EN_TO_ALU
add wave -noupdate /core/MEM_W_EN_TO_ALU
add wave -noupdate /core/ALU_REG_DEST_TO_ALU
add wave -noupdate /core/PC_TO_ALU
add wave -noupdate /core/regD_reg_ALU
add wave -noupdate /core/regD_imme_ALU
add wave -noupdate /core/is_BRANCH_TO_ALU
add wave -noupdate /core/ALU_OP_TO_ALU
add wave -noupdate /core/FUNCTION_TO_ALU
add wave -noupdate /core/reg_s
add wave -noupdate /core/reg_t
add wave -noupdate /core/MEM_TO_REG_TO_ALU
add wave -noupdate /core/regDdata_to_mem
add wave -noupdate /core/regBdata_to_mem
add wave -noupdate /core/zero_to_mem
add wave -noupdate /core/WB_EN_TO_MEM
add wave -noupdate /core/MEM_R_EN_TO_MEM
add wave -noupdate /core/MEM_W_EN_TO_MEM
add wave -noupdate /core/PC_TO_MEM
add wave -noupdate /core/is_BRANCH_TO_MEM
add wave -noupdate /core/MEM_TO_REG_TO_MEM
add wave -noupdate /core/WB_EN_TO_WB
add wave -noupdate /core/MEM_TO_REG_TO_WB
add wave -noupdate /core/alu_result_to_wb
add wave -noupdate /core/read_data_mem_to_wb
add wave -noupdate /core/write_data_to_reg
add wave -noupdate /core/destination_reg
add wave -noupdate /core/RegW_en_to_decode
add wave -noupdate /core/BRANCH_TO_FETCH
add wave -noupdate /core/PCNEXT_TO_FETCH
add wave -noupdate /core/regD_to_wb
add wave -noupdate /core/regD_to_mem
add wave -noupdate /core/is_immediate
add wave -noupdate /core/EN_REG_FETCH
add wave -noupdate /core/EN_REG_DECODE
add wave -noupdate /core/EN_REG_ALU
add wave -noupdate /core/EN_REG_MEM
add wave -noupdate /core/decode_state/registers/regA
add wave -noupdate /core/decode_state/registers/regB
add wave -noupdate /core/decode_state/registers/regD
add wave -noupdate /core/decode_state/registers/data_to_w
add wave -noupdate /core/decode_state/registers/clk
add wave -noupdate /core/decode_state/registers/RegWriteEn
add wave -noupdate /core/decode_state/registers/regA_data
add wave -noupdate /core/decode_state/registers/regB_data
add wave -noupdate -expand /core/decode_state/registers/regfile
add wave -noupdate /core/decode_state/registers/i
add wave -noupdate /core/decode_state/control/clk
add wave -noupdate /core/decode_state/control/reset
add wave -noupdate /core/decode_state/control/instruction
add wave -noupdate /core/decode_state/control/ALU_REG_DEST
add wave -noupdate /core/decode_state/control/is_branch
add wave -noupdate /core/decode_state/control/MEM_R_EN
add wave -noupdate /core/decode_state/control/MEM_W_EN
add wave -noupdate /core/decode_state/control/MEM_TO_REG
add wave -noupdate /core/decode_state/control/WB_EN
add wave -noupdate /core/decode_state/control/ALU_OP
add wave -noupdate /core/decode_state/control/FUNCTION
add wave -noupdate /core/decode_state/control/regA
add wave -noupdate /core/decode_state/control/regB
add wave -noupdate /core/decode_state/control/regD
add wave -noupdate /core/decode_state/control/EN_REG_FETCH
add wave -noupdate /core/decode_state/control/EN_REG_DECODE
add wave -noupdate /core/decode_state/control/EN_REG_ALU
add wave -noupdate /core/decode_state/control/EN_REG_MEM
add wave -noupdate /core/decode_state/control/is_immediate
add wave -noupdate /core/decode_state/control/FUNCTION_INT
add wave -noupdate /core/decode_state/control/ALU_OP_internal
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {833 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 307
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {196 ps} {925 ps}
